version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: legislative_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: legislative_mas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Mapeia o script SQL para rodar na criação do banco
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: